---

- hosts: localhost
  any_errors_fatal: true
  run_once: true
  roles:
    - role: rke2_download

- hosts: rke2_servers
  any_errors_fatal: true
  become: yes
  roles:
    - role: rke2_server
  serial: 3

- hosts: rke2_agents
  any_errors_fatal: true
  become: yes
  roles:
    - role: rke2_agent
  serial: 3
